name: 📊 Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📊 Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: chekerh
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Tunis
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_traffic: yes
          output_action: commit
          committer_message: "update metrics"
