name: 🦉 Owl Flight Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🦉 Generate Owl Flight SVG
        uses: Platane/snk@v3
        with:
          github_user_name: chekerh
          outputs: dist/owl.svg
          palette: github-dark
          color_snake: "gold"
          color_dots: "#E5E5E5"

      - name: 🚀 Deploy Owl SVG
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
