name: 🦉 Owl Flight Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🦉 Generate Owl Flight SVG
        uses: Platane/snk@v3
        with:
          github_user_name: chekerh
          outputs: dist/owl.svg
          palette: "github-dark"
          color_snake: "gold"        # owl trail color
          color_dots: "#E5E5E5"      # dots color
      - name: 🚀 Deploy Owl SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
